package hypothesis

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/trialanderror-eng/lolo/internal/evidence"
	"github.com/trialanderror-eng/lolo/internal/incident"
	"github.com/trialanderror-eng/lolo/internal/llm"
)

// LLMRanker wraps another Ranker and rewrites the Reasoning field of the
// top-N hypotheses with a natural-language narrative generated by a local
// LLM. Scores and evidence are untouched — the ranking is still
// deterministic, the LLM is a prose layer on top of structured findings.
//
// If the LLM call fails or times out, the original Reasoning is preserved.
// An investigation never fails on LLM availability.
type LLMRanker struct {
	Inner   Ranker
	Client  llm.Client
	TopN    int           // 0 → narrate all; otherwise top N by score
	Timeout time.Duration // per-call cap; default 10s
}

const systemPrompt = `You are an SRE reading an incident RCA report. Given an incident and supporting evidence from observability tools, write 2 to 3 concise factual sentences describing the most likely root cause and why the evidence points to it. Avoid speculation beyond what the evidence supports. Do not repeat the incident ID or restate the summary. Do not propose remediations unless the evidence clearly implies one.`

func (r LLMRanker) Rank(ctx context.Context, inc incident.Incident, ev []evidence.Evidence) ([]Hypothesis, error) {
	hs, err := r.Inner.Rank(ctx, inc, ev)
	if err != nil || len(hs) == 0 {
		return hs, err
	}
	if r.Client == nil {
		return hs, nil
	}

	n := len(hs)
	if r.TopN > 0 && r.TopN < n {
		n = r.TopN
	}
	for i := 0; i < n; i++ {
		if narrative := r.narrate(ctx, inc, hs[i]); narrative != "" {
			hs[i].Reasoning = narrative
		}
	}
	return hs, nil
}

func (r LLMRanker) narrate(ctx context.Context, inc incident.Incident, h Hypothesis) string {
	timeout := r.Timeout
	if timeout <= 0 {
		timeout = 10 * time.Second
	}
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	out, err := r.Client.Narrate(ctx, systemPrompt, buildUserPrompt(inc, h))
	if err != nil {
		log.Printf("llm narrate (incident=%s hypothesis=%q): %v", inc.ID, h.Summary, err)
		return ""
	}
	return out
}

func buildUserPrompt(inc incident.Incident, h Hypothesis) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Incident: %s\n", inc.ID)
	fmt.Fprintf(&b, "Signal: %s\n", inc.Signal.Summary)
	if scope := formatScope(inc.Scope); scope != "" {
		fmt.Fprintf(&b, "Scope: %s\n", scope)
	}
	fmt.Fprintf(&b, "Window: %s\n\n", inc.Window)
	fmt.Fprintf(&b, "Candidate root cause: %s (confidence %.2f)\n\n", h.Summary, h.Score)

	if len(h.Evidence) > 0 {
		b.WriteString("Supporting evidence:\n")
		for _, e := range h.Evidence {
			fmt.Fprintf(&b, "- [%s %s at %s] %s\n",
				e.Source, e.Kind, e.At.Format(time.RFC3339), truncate(e.Summary, 240))
		}
	}
	b.WriteString("\nExplain the likely root cause in 2-3 sentences.")
	return b.String()
}

func formatScope(s incident.Scope) string {
	parts := []string{}
	if len(s.Services) > 0 {
		parts = append(parts, "services="+strings.Join(s.Services, ","))
	}
	if len(s.Namespaces) > 0 {
		parts = append(parts, "namespaces="+strings.Join(s.Namespaces, ","))
	}
	if len(s.Clusters) > 0 {
		parts = append(parts, "clusters="+strings.Join(s.Clusters, ","))
	}
	if len(s.Repos) > 0 {
		parts = append(parts, "repos="+strings.Join(s.Repos, ","))
	}
	return strings.Join(parts, " ")
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
